# Before Script
before_script:
    - export LC_CTYPE=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - env
    - locale
    - pod --version
    - pod setup --silent
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

stages:
    - build

Build:
  stage: build
  script:
    - set -o pipefail
    - echo Check if the library described by the podspec can be built
    - pod lib lint
    - echo Build the library
    - xcodebuild clean build -workspace LUAutocompleteView.xcworkspace -scheme LUAutocompleteView -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
    - echo Build the example
    - pod install --project-directory=LUAutocompleteViewExample
    - xcodebuild clean build -workspace LUAutocompleteView.xcworkspace -scheme LUAutocompleteViewExample -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
  tags:
    - ios